#!/usr/bin/env python3
"""
reportgen.py — assemble the final disclosure report from validated findings.

Consumes the engagement blackboard (findings marked PASS by triage, non-duplicate)
and renders a HackerOne-ready disclosure report in the style of the
Claude-BugHunter `report-writing` / `evidence-hygiene` skills:

  - title + summary
  - per-finding: description, reproduction steps (curl), impact, evidence list,
    remediation
  - CVSS 3.1 vector per finding (best-effort from severity)
  - a pre-submission checklist derived from the 7-Question Gate
"""
import datetime
import json
import os
import re

SEVERITY_TO_CVSS = {
    "critical": "AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
    "high": "AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:L/A:L",
    "medium": "AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N",
    "low": "AV:N/AC:L/PR:L/UI:R/S:U/C:L/I:N/A:N",
    "info": "AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N",
}


def _severity(f: dict) -> str:
    sev = (f.get("severity") or "medium").lower()
    if sev not in SEVERITY_TO_CVSS:
        sev = "medium"
    return sev


def _evidence_list(f: dict, evidence_root: str = "") -> list[str]:
    ev = f.get("evidence") or []
    out = []
    for e in ev:
        if isinstance(e, str):
            out.append(e if not evidence_root else os.path.join(evidence_root, e))
        else:
            out.append(f"{e.get('type','')}: {e.get('path','')}")
    return out


def _clean_step(s: str) -> str:
    """Strip leading step numbers so reportgen's own numbering is authoritative."""
    s = s.strip()
    return re.sub(r"^\d+[.)]\s*", "", s)


def render_finding_markdown(f: dict, evidence_root: str = "") -> str:
    sev = _severity(f)
    steps = f.get("reproduction_steps") or f.get("steps") or []
    if isinstance(steps, str):
        steps = [s for s in steps.splitlines() if s.strip()]
    steps = [_clean_step(s) for s in steps]
    lines = [
        f"### {f.get('title', f.get('id', 'Untitled'))}",
        "",
        f"- **Severity:** {sev.capitalize()}",
        f"- **Vuln class:** {f.get('vuln_class', 'n/a')}",
        f"- **Endpoint:** `{f.get('endpoint', 'n/a')}` ({f.get('method', 'GET')})",
        f"- **CVSS 3.1:** `{SEVERITY_TO_CVSS[sev]}`",
        f"- **Finding ID:** {f.get('id')}",
        "",
        "#### Summary",
        "",
        f.get("summary", f.get("description", "")),
        "",
        "#### Steps to reproduce",
        "",
    ]
    if not steps:
        lines.append("_(fill in: curl commands per step)_")
    else:
        for i, s in enumerate(steps, 1):
            lines.append(f"{i}. {s}")
    impact = f.get("impact")
    if impact:
        lines += ["", "#### Impact", "", impact]
    ev = _evidence_list(f, evidence_root)
    if ev:
        lines += ["", "#### Supporting evidence", ""]
        for e in ev:
            lines.append(f"- `{e}`")
    rem = f.get("remediation")
    if rem:
        lines += ["", "#### Remediation", "", rem]
    lines.append("")
    return "\n".join(lines)


def build_report(engagement, platform: str = "h1", evidence_root: str = "") -> str:
    target = engagement.summary().get("target")
    state = engagement.state()
    findings = [f for f in engagement.findings()
                if f.get("status") not in ("duplicate", "rejected", "false_positive")]
    today = datetime.date.today().isoformat()
    lines = [
        f"# Security Vulnerability Report — {target}",
        "",
        f"_Prepared for responsible disclosure via {platform.upper()} · {today}_",
        "",
        "## Executive summary",
        "",
        f"This report documents {len(findings)} validated finding(s) on {target} "
        f"discovered during an authorized, in-scope engagement. Each finding includes "
        "reproduction steps, supporting evidence, impact, and remediation guidance.",
        "",
        "## Findings overview",
        "",
        "| # | Finding | Severity | Endpoint |",
        "|---|---------|----------|----------|",
    ]
    for i, f in enumerate(findings, 1):
        sev = _severity(f)
        lines.append(f"| {i} | {f.get('title','')} | {sev.capitalize()} | `{f.get('endpoint','')}` |")
    lines.append("")
    for f in findings:
        lines.append(render_finding_markdown(f, evidence_root))
    lines += [
        "## Pre-submission checklist",
        "",
        "- [ ] Each finding passes the 7-Question Gate (Q1..Q7) — no KILL left in this report",
        "- [ ] No duplicate of an existing public report (duplicatecheck ran)",
        "- [ ] Evidence redacted: no cookies, session tokens, or third-party PII in attachments",
        "- [ ] Reproduction steps re-run exactly as written against the current target state",
        "- [ ] Impact is on the program's accepted-impact list",
        "- [ ] All assets touched are within program scope",
        "",
        "_Generated by MultiHunter. Review every section before submission._",
    ]
    return "\n".join(lines)


def _selftest():
    import tempfile
    from blackboard import Engagement
    d = tempfile.mkdtemp()
    try:
        e = Engagement(base=d, target="acme.com").create("acme.com")
        e.add_finding({
            "title": "IDOR on /api/user/{id}", "vuln_class": "IDOR", "severity": "high",
            "endpoint": "https://a.acme.com/api/user/1", "method": "GET",
            "summary": "Authenticated user can read another user's profile.",
            "reproduction_steps": ["1. Login as user A",
                                   "2. curl -H 'Cookie: s=a' https://a.acme.com/api/user/2",
                                   "3. Observe user B's PII in the response"],
            "impact": "Full PII disclosure for any account.",
            "remediation": "Enforce object-level authorization.",
        })
        e.add_finding({"title": "Duplicate", "vuln_class": "IDOR", "severity": "high",
                       "endpoint": "https://a.acme.com/api/user/3", "method": "GET",
                       "status": "duplicate"})
        report = build_report(e, "h1")
        assert "IDOR on /api/user/{id}" in report
        assert "Duplicate" not in report
        assert "AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:L/A:L" in report
        print("reportgen.py self-test: PASS")
    finally:
        import shutil
        shutil.rmtree(d, ignore_errors=True)


if __name__ == "__main__":
    _selftest()